# Generated by Django 4.0.3 on 2022-04-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_user_email_alter_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='song_id',
        ),
        migrations.AddField(
            model_name='level',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='song_name',
            field=models.CharField(default='Name1', max_length=256),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
