# Generated by Django 4.0.4 on 2022-04-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='game_time',
        ),
    ]
