# Generated by Django 4.0.4 on 2022-04-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_attempt_game_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVariables',
            fields=[
                ('variables_id', models.AutoField(primary_key=True, serialize=False)),
                ('lvl', models.IntegerField()),
                ('video', models.IntegerField()),
                ('Hs1', models.IntegerField()),
                ('Hs2', models.IntegerField()),
                ('Hs3', models.IntegerField()),
                ('FirstTime', models.IntegerField()),
                ('score', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
    ]
