# Generated by Django 4.0.4 on 2022-05-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_gamevariables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('session_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
    ]
